export const SHOW_LOADING = "SHOW_LOADING"
export const HIDE_LOADING = "HIDE_LOADING"

export const CHECK_LOGIN = "CHECK_LOGIN"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERR = "LOGIN_ERR"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERR = "REGISTER_ERR"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"

export const FETCH_NOTE_REQUEST = "FETCH_NOTE_REQUEST"
export const FETCH_NOTE_SUCCESS = "FETCH_NOTE_SUCCESS"
export const FETCH_NOTE_ERR = "FETCH_NOTE_ERR"

export const RESET_NOTE = "RESET_NOTE"

export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST"
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS"
export const ADD_NOTE_ERR = "ADD_NOTE_ERR"

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST"
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS"
export const UPDATE_NOTE_ERR = "UPDATE_NOTE_ERR"


export const REMOVE_NOTE_REQUEST = "REMOVE_NOTE_REQUEST"
export const REMOVE_NOTE_SUCCESS = "REMOVE_NOTE_SUCCESS"
export const REMOVE_NOTE_ERR = "REMOVE_NOTE_ERR"

export const CHECKER_NOTE_REQUEST = "CHECKER_NOTE_REQUEST"
export const CHECKER_NOTE_SUCCESS = "CHECKER_NOTE_SUCCESS"
export const CHECKER_NOTE_ERR = "CHECKER_NOTE_ERR"

export const SHOW_POPUP = "SHOW_POPUP"
export const HIDE_POPUP = "HIDE_POPUP"

export const SHOW_CONFIRM = "SHOW_CONFIRM"
export const HIDE_CONFIRM = "HIDE_CONFIRM"


export const EDIT_TEXT = "EDIT_TEXT"

